# Generated by Django 4.2.4 on 2023-08-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctors',
            new_name='doctor',
        ),
    ]
